### ISSUE TITLE
is there a way to change the menu background?

### ISSUE THREAD

**Issue by Sebacho-Barajas** [liufengting/FTPopOverMenu#16]
I'd like to change the background to dark or light blur.
can you add this feature ?

**Comment by liufengting** [comment]
try [this](https://github.com/liufengting/FTPopMenu)

**Comment by Sebacho-Barajas** [comment]
@liufengting  [](https://github.com/liufengting/FTPopMenu) isn't what I'm looking for because i need to use different types of blur (UIBlurEffectStyleExtraLight,
    UIBlurEffectStyleLight,
    UIBlurEffectStyleDark)
