### ISSUE TITLE
为什么bar button item的需要传event的参数

### ISSUE THREAD

**Issue by lifengios** [liufengting/FTPopOverMenu#18]
使用文档里面写的 如果是 bar button item点击出来的pop，使用了show from event 方法，这个event 参数 有什么用，不是太懂，好像在item 的 action 方法里面 使用 show form sender view 也是可以的。

**Comment by liufengting** [comment]
我当时的想法是通过event获取点击的frame，show form sender view我没有试过。

**Comment by jiaohaibin** [comment]
UIBarButtonItem的响应函数里面没有event呀。

**Comment by liufengting** [comment]
demo里有示例代码，event是为了确定点击位置
