### ISSUE TITLE
请问能增加一个选中颜色吗？

### ISSUE THREAD

**Issue by aipaiSpaceMan** [liufengting/FTPopOverMenu#19]
默认选中第几个，这样的选项有办法实现吗，并且默认选中的菜单字体颜色由另外一个属性去赋值

**Comment by lilin87788** [comment]
同样需要一个设置一个选中颜色的设置

**Comment by liufengting** [comment]
@aipaiSpaceMan @lilin87788 最近刚好有空，这几天等我消息

**Comment by liufengting** [comment]
![qq20180126-223843](https://user-images.githubusercontent.com/4414522/35444519-c0f0a708-02e9-11e8-9709-831b91003f54.png)

**Comment by liufengting** [comment]
1.3.4
