### ISSUE TITLE
api建议

### ISSUE THREAD

**Issue by nenhall** [liufengting/FTPopOverMenu#26]
你这个做得很不错！但api属性不够灵活，属性命令应更贴近苹果的风格才好！
例如：
1，设置属性的不要用单例来控制，在不同界面有可能出现不同属性、色调；
2，FTPopOverMenuConfiguration应该当作一个属性来传；你现在这个如果我使用继承，在init去重设FTPopOverMenuConfiguration属性是无效，导致我每写一次都必须要跟着在+(void)show.....函数前写一大堆配置；
3，返回参数应该返回本类，然后可以通过返回实例再修改对应的popview属性；
4，我想改个背景色，这个情况下应该叫backgroundcolor更恰当，而不是tintColor；backgroundView这个背景颜色也没法改。

个人使用后的一些建议，谢谢！

**Comment by liufengting** [comment]
@nenhall 收到你的建议很开心，我已经根据你的建议修改发布了2.0.0，主要修改了1，2，4. 至于第三条，我看了下代码里很多属性没有写get方法，外部设置属性有部分不生效，等后面会添加上。
