### ISSUE TITLE
Out of screen

### ISSUE THREAD

**Issue by kakkuk** [liufengting/FTPopOverMenu#4]
![simulator screen shot 14 aug 2016 12 12 52](https://cloud.githubusercontent.com/assets/3705620/17648317/80013b0e-6218-11e6-9618-63c832ad3c63.png)

popup menu out of screen, is it possible to custom height for popup menu?
thank you

**Comment by liufengting** [comment]
#3 maybe have the solution for you。when you have too many menus, make it scrollable.

**Comment by liufengting** [comment]
check out the newest change at https://github.com/liufengting/FTPopOverMenu/blob/master/CHANGELOG.md

I have added this feature.

**Comment by kakkuk** [comment]
you are greet man, thank you
you must add menu height like this

you must add this feature
#define FTDefaultMenuHeight         200.0

there is only menu width but no height
#define FTDefaultMenuWidth          120.0

**Comment by liufengting** [comment]
I will add a feature for custom width

**Comment by liufengting** [comment]
Sorry, I decided not to add this feature.  Because in order to support both portrait and landscape, and auto enable the scrolling, I don't think adding height constrain is necessary. If you do want this feature, I could create a branch and make a demo for you. Thanks : )
