### ISSUE TITLE
组件化依赖FTPopOverMenu出错问题

### ISSUE THREAD

**Issue by devcxm** [liufengting/FTPopOverMenu#46]
我公司项目的组件依赖FTPopOverMenu，但是作者的FTPopOverMenu.podspec没有声明s.ios.deployment_target = '9.0'，这样在pod install安装后FTPopOverMenu项目的iOS Deploment Target为iOS 4.3，编译会出错，希望作者早日加上这个设置。

>PS： 目前通过修改Podfile脚本解决
```
 post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] ='9.0'
          end
      end
  end
```

**Comment by liufengting** [comment]
@devcxm 收到，会尽快更新

**Comment by liufengting** [comment]
@devcxm 已更新2.1.0，加入了s.ios.deployment_target = '9.0'
