### ISSUE TITLE
第一个菜单选项，边缘点不中？

### ISSUE THREAD

**Issue by JenkinChen** [liufengting/FTPopOverMenu#5]

**Comment by liufengting** [comment]
除了箭头，其他都可以点中的吧，我试了一下可以，具体哪里点不中，给个截图过来。发邮件或者加我QQ： 157121900.

**Comment by JenkinChen** [comment]
![a0803659-16cf-4223-b6ae-a068f377921c](https://cloud.githubusercontent.com/assets/14823088/18242588/9cf9962a-7389-11e6-938b-2d455ccb0ca4.png)
红色区域
