### ISSUE TITLE
按钮动画的缩放偶现效果会被中断

### ISSUE THREAD

**Issue by bob2077** [liufengting/FTPopOverMenu#52]
这应该是一个bug

**Comment by liufengting** [comment]
` 
    [UIView animateWithDuration:self.config.animationDuration
                     animations:^{

                     }completion:^(BOOL finished) {
                         if (finished) {
                            
                         }
                     }];
`

`
                         if (finished) {
                            
                         }
`
这个if判断应该去掉可以解决。

**Comment by bob2077** [comment]
不是上边的原因。据我排查，是因为初始化视图时使用异步主线程造成动画可能不被执行。

**Comment by liufengting** [comment]
好的，周末会更新版本解决，更新后通知你。发自我的 iPhone在 2022年12月2日，10:09，bob ***@***.***> 写道：﻿
不是上边的原因。据我排查，是因为初始化视图时使用异步主线程造成动画可能不被执行。

**Comment by liufengting** [comment]
2.1.3
