### ISSUE TITLE
遇到引用问题，调用FTPopOverMenu的VC无法释放

### ISSUE THREAD

**Issue by jiazufei** [liufengting/FTPopOverMenu#7]

**Comment by liufengting** [comment]
FTPopOverMenu是单例，应该不会释放，具体vc在何时释放，和FTPopOverMenu应该没有关系，强引用了单例？ARC一般情况下不需要考虑什么释放，可以加我QQ：157121900详聊。

**Comment by jiazufei** [comment]
点击回调中写了个方法（并没有封装成一个小方法），调用了VC的一些属性，尽管weakSelf了，还是无法释放。
最后的解决方法，将回调中的代码封装成了一个小方法，就可以释放了
