### ISSUE TITLE
菜单高度计算问题

### ISSUE THREAD

**Issue by gokenpei** [liufengting/FTPopOverMenu#8]
非常好的弹出菜单实现。
adjustPopOverMenu 里面计算高度没有用全局配置高度，会导致高度定制时候，总体高度不对。
另外，建议能实现直接传菜单图片数组，方便采用 FontAwesome。

**Comment by liufengting** [comment]
已经发布pod 1.2.2 版本解决这个问题。
实现直接传菜单图片数组，我重新开个分支
